### ISSUE TITLE
Q1_Numbers についての提案

### ISSUE THREAD

**Issue by arowM** [jinjor/elm-drill#2]
もしかしたら以下の内容を補足してもいいのかな〜っていう提案です。
どこまでこのドリルがカバーするかによって適宜取り入れていただければと思います。

* `{-` から `-}` で囲まれた部分がコメントであること
* モジュールについてのコメントや、関数の説明に対しては `{-|` と `-}` で囲む「お作法」があること
* `a -> b` が `a` を引数にとって `b` を返り値にする関数の型であること
* `number` は `Int` または `Float` のどちらかであることを示すが、 `number -> number` は `Int -> Float` みたいにはならないこと

**Comment by jinjor** [comment]
レビューありがとうございます！
迷いましたが、基本的に文法の説明は本家などのドキュメントを参照してもらいたいので無しにしました。（３番目だけあってもいい気がしたんですが、例が全部 Int -> Int か Float -> Float で引数と戻り値の型が同じで説明しにくかったです。。）
他の issue/PR はだいたい対応しました。
